#ifndef MERLINCOMMANDSDEF_H
#define MERLINCOMMANDSDEF_H

#define SOFTWAREVERSION "SOFTWAREVERSION"
#define STARTACQUISITION "STARTACQUISITION"
#define STOPACQUISITION "STOPACQUISITION"
#define SOFTTRIGGER "SOFTTRIGGER"
#define ABORT "ABORT"
#define SELFTEST "SELFTEST"
#define NOISEEQUALIZATION "NOISEEQUALIZATION"
#define STOPEQUALIZATION  "STOPEQUALIZATION"
#define FLATFIELDCORRECTION "FLATFIELDCORRECTION"
#define THSCAN "THSCAN"
#define COLOURMODE "COLOURMODE"
#define CHARGESUMMING "CHARGESUMMING"
#define GAIN "GAIN"
#define CONTINUOUSRW "CONTINUOUSRW"
#define ENABLECOUNTER1 "ENABLECOUNTER1"

//threshold
#define THRESHOLD0 "THRESHOLD0"
#define THRESHOLD1 "THRESHOLD1"
#define THRESHOLD2 "THRESHOLD2"
#define THRESHOLD3 "THRESHOLD3"
#define THRESHOLD4 "THRESHOLD4"
#define THRESHOLD5 "THRESHOLD5"
#define THRESHOLD6 "THRESHOLD6"
#define THRESHOLD7 "THRESHOLD7"
//per chip
#define THRESHOLD0CHIP "THRESHOLD0CHIP"
#define THRESHOLD1CHIP "THRESHOLD1CHIP"
#define THRESHOLD2CHIP "THRESHOLD2CHIP"
#define THRESHOLD3CHIP "THRESHOLD3CHIP"
#define THRESHOLD4CHIP "THRESHOLD4CHIP"
#define THRESHOLD5CHIP "THRESHOLD5CHIP"
#define THRESHOLD6CHIP "THRESHOLD6CHIP"
#define THRESHOLD7CHIP "THRESHOLD7CHIP"
//end of threshold
#define OPERATINGENERGY "OPERATINGENERGY"
#define COUNTERDEPTH "COUNTERDEPTH"
//temps and humidity
#define FPGATEMPERATURE "FPGATEMPERATURE"
#define BOARDTEMPERATURE "BOARDTEMPERATURE"
#define CHIPTEMPERATURE "CHIPTEMPERATURE"
#define HUMIDITY "HUMIDITY"
//end temps and humidity
#define ACQUISITIONTIME "ACQUISITIONTIME"
#define ACQUISITIONPERIOD "ACQUISITIONPERIOD"
#define NUMFRAMESTOACQUIRE "NUMFRAMESTOACQUIRE"
//threshold scan
#define THSTART "THSTART"
#define THSTOP  "THSTOP"
#define THSTEP  "THSTEP"
#define THFRAMES "THFRAMES"  //does not exist in M doc
#define THPATH   "THPATH"    //does not exist in M doc
#define THSCAN   "THSCAN"    //does not exist in M doc (this is an CMD)
//end of threshold scan
#define PROFILES "PROFILES"
#define TRIGGERMODE  "TRIGGERMODE"
#define INHIBITSHUTTER "INHIBITSHUTTER"
#define FILEENABLE "FILEENABLE"
#define FILEDIRECTORY "FILEDIRECTORY"
//masking pixels
#define MASKPIXEL "MASKPIXEL"       //does not exist in M doc
#define UNMASKPIXEL "UNMASKPIXEL"   //does not exist in M doc
#define MASKEDMATRIXPATH "MASKEDMATRIXPATH" //does not exist in M doc(set and get the path of masked pixel matrix)
//end of masking pixels
#define EQUALIZATIONFILES "EQUALIZATIONFILE"
#define CONFIGFILE  "CONFIGFILE"
#define SAVECONFIGS "SAVECONFIGS"
//#define EQUALIZATIONFILE  "EQUALIZATIONFILE"
#define DOEQUALIZATION "DOEQUALIZATION"
#define SLOPES "SLOPE"
#define OFFSETS "OFFSET"
#define RESETSLOPESANDOFFSETS "RESETSLOPESANDOFFSETS"
//testpulses
#define TPINJECTIONCHARGE "TPINJECTIONCHARGE"
#define TPLENGTH          "TPLENGTH"
#define TPPERIOD           "TPPERIOD"
#define TPPIXELSPACING      "TPPIXELSPACING"
//end of testpulses

//server status
#define SERVERSTATUS "SERVERSTATUS"

//end of server status







#endif // MERLINCOMMANDSDEF_H
