#ifndef MERLINCOMMANDSDEF_H
#define MERLINCOMMANDSDEF_H

#define GETSOFTWAREREVISION "GETSOFTWAREREVISION"
#define STARTACQUISITION "STARTACQUISITION"
#define STOPACQUISITION "STOPACQUISITION"
#define SOFTTRIGGER "SOFTTRIGGER"
#define ABORT "ABORT"
#define SELFTEST "SELFTEST"
#define NOISEEQUALIZATION "NOISEEQUALIZATION"
#define FLATFIELDCORRECTION "FLATFIELDCORRECTION"
#define THSCAN "THSCAN"
#define COLOURMODE "COLOURMODE"
#define CHARGESUMMING "CHARGESUMMING"
#define GAIN "GAIN"
#define CONTINUOUSRW "CONTINUOUSRW"
#define ENABLECOUNTER1 "ENABLECOUNTER1"
#define THRESHOLD0 "THRESHOLD0"
#define THRESHOLD1 "THRESHOLD1"
#define THRESHOLD2 "THRESHOLD2"
#define THRESHOLD3 "THRESHOLD3"
#define THRESHOLD4 "THRESHOLD4"
#define THRESHOLD5 "THRESHOLD5"
#define THRESHOLD6 "THRESHOLD6"
#define THRESHOLD7 "THRESHOLD7"
#define OPERATINGENERGY "OPERATINGENERGY"
#define COUNTERDEPTH "COUNTERDEPTH"
#define TEMPERATURE "TEMPERATURE"


#endif // MERLINCOMMANDSDEF_H
