# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wafer/WaferProbing.ui'
#
# Created: Wed Oct 29 13:19:31 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/cd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBurn = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/burn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBurn.setIcon(icon1)
        self.toolBurn.setIconSize(QtCore.QSize(48, 48))
        self.toolBurn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBurn.setObjectName("toolBurn")
        self.horizontalLayout.addWidget(self.toolBurn)
        self.toolStartOne = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolStartOne.setIcon(icon2)
        self.toolStartOne.setIconSize(QtCore.QSize(48, 48))
        self.toolStartOne.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolStartOne.setObjectName("toolStartOne")
        self.horizontalLayout.addWidget(self.toolStartOne)
        self.toolStartWafer = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/player_fwd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolStartWafer.setIcon(icon3)
        self.toolStartWafer.setIconSize(QtCore.QSize(48, 48))
        self.toolStartWafer.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolStartWafer.setObjectName("toolStartWafer")
        self.horizontalLayout.addWidget(self.toolStartWafer)
        self.toolStop = QtGui.QToolButton(self.centralwidget)
        self.toolStop.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolStop.setIcon(icon4)
        self.toolStop.setIconSize(QtCore.QSize(48, 48))
        self.toolStop.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolStop.setObjectName("toolStop")
        self.horizontalLayout.addWidget(self.toolStop)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(36)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.waferNumber = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waferNumber.sizePolicy().hasHeightForWidth())
        self.waferNumber.setSizePolicy(sizePolicy)
        self.waferNumber.setBaseSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(36)
        font.setWeight(75)
        font.setBold(True)
        self.waferNumber.setFont(font)
        self.waferNumber.setObjectName("waferNumber")
        self.horizontalLayout.addWidget(self.waferNumber)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.textEdit.setFont(font)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOperation = QtGui.QMenu(self.menubar)
        self.menuOperation.setObjectName("menuOperation")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Tests = QtGui.QMenu(self.menu_Settings)
        self.menu_Tests.setObjectName("menu_Tests")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBurn = QtGui.QAction(MainWindow)
        self.actionBurn.setCheckable(False)
        self.actionBurn.setChecked(False)
        self.actionBurn.setIcon(icon1)
        self.actionBurn.setObjectName("actionBurn")
        self.actionStartOne = QtGui.QAction(MainWindow)
        self.actionStartOne.setCheckable(False)
        self.actionStartOne.setChecked(False)
        self.actionStartOne.setIcon(icon2)
        self.actionStartOne.setObjectName("actionStartOne")
        self.actionDACs = QtGui.QAction(MainWindow)
        self.actionDACs.setCheckable(True)
        self.actionDACs.setObjectName("actionDACs")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionShutter = QtGui.QAction(MainWindow)
        self.actionShutter.setCheckable(True)
        self.actionShutter.setChecked(True)
        self.actionShutter.setObjectName("actionShutter")
        self.actionOthers = QtGui.QAction(MainWindow)
        self.actionOthers.setCheckable(True)
        self.actionOthers.setObjectName("actionOthers")
        self.actionEqualize = QtGui.QAction(MainWindow)
        self.actionEqualize.setEnabled(False)
        self.actionEqualize.setObjectName("actionEqualize")
        self.actionTrimsReset = QtGui.QAction(MainWindow)
        self.actionTrimsReset.setEnabled(True)
        self.actionTrimsReset.setObjectName("actionTrimsReset")
        self.actionTrimsSetAll = QtGui.QAction(MainWindow)
        self.actionTrimsSetAll.setObjectName("actionTrimsSetAll")
        self.actionTrimsLoad = QtGui.QAction(MainWindow)
        self.actionTrimsLoad.setObjectName("actionTrimsLoad")
        self.actionMaskAll = QtGui.QAction(MainWindow)
        self.actionMaskAll.setObjectName("actionMaskAll")
        self.actionUnmaskAll = QtGui.QAction(MainWindow)
        self.actionUnmaskAll.setObjectName("actionUnmaskAll")
        self.actionMaskLoad = QtGui.QAction(MainWindow)
        self.actionMaskLoad.setObjectName("actionMaskLoad")
        self.action_Enable_all = QtGui.QAction(MainWindow)
        self.action_Enable_all.setObjectName("action_Enable_all")
        self.action_Disable_all = QtGui.QAction(MainWindow)
        self.action_Disable_all.setObjectName("action_Disable_all")
        self.action_Load_3 = QtGui.QAction(MainWindow)
        self.action_Load_3.setObjectName("action_Load_3")
        self.actionHitRate = QtGui.QAction(MainWindow)
        self.actionHitRate.setCheckable(True)
        self.actionHitRate.setObjectName("actionHitRate")
        self.actionDemoConfig = QtGui.QAction(MainWindow)
        self.actionDemoConfig.setCheckable(True)
        self.actionDemoConfig.setObjectName("actionDemoConfig")
        self.actionConnectSPIDR = QtGui.QAction(MainWindow)
        self.actionConnectSPIDR.setObjectName("actionConnectSPIDR")
        self.actionConnectDemo = QtGui.QAction(MainWindow)
        self.actionConnectDemo.setObjectName("actionConnectDemo")
        self.actionOutputs = QtGui.QAction(MainWindow)
        self.actionOutputs.setCheckable(True)
        self.actionOutputs.setChecked(True)
        self.actionOutputs.setObjectName("actionOutputs")
        self.actionMaskSave = QtGui.QAction(MainWindow)
        self.actionMaskSave.setObjectName("actionMaskSave")
        self.actionTrimsSave = QtGui.QAction(MainWindow)
        self.actionTrimsSave.setObjectName("actionTrimsSave")
        self.actionLoadConfiguration = QtGui.QAction(MainWindow)
        self.actionLoadConfiguration.setEnabled(False)
        self.actionLoadConfiguration.setObjectName("actionLoadConfiguration")
        self.actionSaveConfiguration = QtGui.QAction(MainWindow)
        self.actionSaveConfiguration.setEnabled(False)
        self.actionSaveConfiguration.setObjectName("actionSaveConfiguration")
        self.actionDisconect = QtGui.QAction(MainWindow)
        self.actionDisconect.setEnabled(False)
        self.actionDisconect.setObjectName("actionDisconect")
        self.actionConnectSPIDR_2 = QtGui.QAction(MainWindow)
        self.actionConnectSPIDR_2.setObjectName("actionConnectSPIDR_2")
        self.actionDemo = QtGui.QAction(MainWindow)
        self.actionDemo.setObjectName("actionDemo")
        self.actionFullScreen = QtGui.QAction(MainWindow)
        self.actionFullScreen.setCheckable(True)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.actionAboutSPIDR = QtGui.QAction(MainWindow)
        self.actionAboutSPIDR.setObjectName("actionAboutSPIDR")
        self.actionSPIDRSettings = QtGui.QAction(MainWindow)
        self.actionSPIDRSettings.setEnabled(True)
        self.actionSPIDRSettings.setObjectName("actionSPIDRSettings")
        self.actionSPIDRAbout = QtGui.QAction(MainWindow)
        self.actionSPIDRAbout.setEnabled(False)
        self.actionSPIDRAbout.setObjectName("actionSPIDRAbout")
        self.actionDummyGenerator = QtGui.QAction(MainWindow)
        self.actionDummyGenerator.setCheckable(True)
        self.actionDummyGenerator.setObjectName("actionDummyGenerator")
        self.actionVisualisation = QtGui.QAction(MainWindow)
        self.actionVisualisation.setCheckable(True)
        self.actionVisualisation.setObjectName("actionVisualisation")
        self.actionSPIDRSettings1 = QtGui.QAction(MainWindow)
        self.actionSPIDRSettings1.setObjectName("actionSPIDRSettings1")
        self.actionStartWafer = QtGui.QAction(MainWindow)
        self.actionStartWafer.setIcon(icon3)
        self.actionStartWafer.setObjectName("actionStartWafer")
        self.actionList = QtGui.QAction(MainWindow)
        self.actionList.setEnabled(False)
        self.actionList.setObjectName("actionList")
        self.actionProbestationSettings = QtGui.QAction(MainWindow)
        self.actionProbestationSettings.setObjectName("actionProbestationSettings")
        self.actionList_2 = QtGui.QAction(MainWindow)
        self.actionList_2.setEnabled(False)
        self.actionList_2.setObjectName("actionList_2")
        self.actionVerbose = QtGui.QAction(MainWindow)
        self.actionVerbose.setCheckable(True)
        self.actionVerbose.setObjectName("actionVerbose")
        self.menuFile.addAction(self.actionExit)
        self.menuOperation.addAction(self.actionBurn)
        self.menuOperation.addAction(self.actionStartOne)
        self.menuOperation.addAction(self.actionStartWafer)
        self.menuHelp.addAction(self.actionAbout)
        self.menu_Tests.addAction(self.actionList_2)
        self.menu_Tests.addSeparator()
        self.menu_Settings.addAction(self.actionSPIDRSettings)
        self.menu_Settings.addAction(self.actionProbestationSettings)
        self.menu_Settings.addAction(self.menu_Tests.menuAction())
        self.menu_Settings.addAction(self.actionVerbose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Timepix3 Wafer Probing", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBurn.setText(QtGui.QApplication.translate("MainWindow", "Burn efuses", None, QtGui.QApplication.UnicodeUTF8))
        self.toolStartOne.setText(QtGui.QApplication.translate("MainWindow", "Start One", None, QtGui.QApplication.UnicodeUTF8))
        self.toolStartWafer.setText(QtGui.QApplication.translate("MainWindow", "Start Wafer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOperation.setTitle(QtGui.QApplication.translate("MainWindow", "&Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tests.setTitle(QtGui.QApplication.translate("MainWindow", "&Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBurn.setText(QtGui.QApplication.translate("MainWindow", "&Burn efuses", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartOne.setText(QtGui.QApplication.translate("MainWindow", "Probe &One", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDACs.setText(QtGui.QApplication.translate("MainWindow", "&DACs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShutter.setText(QtGui.QApplication.translate("MainWindow", "&Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOthers.setText(QtGui.QApplication.translate("MainWindow", "&Others", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEqualize.setText(QtGui.QApplication.translate("MainWindow", "&Equalize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrimsReset.setText(QtGui.QApplication.translate("MainWindow", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrimsSetAll.setText(QtGui.QApplication.translate("MainWindow", "&Set All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrimsLoad.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaskAll.setText(QtGui.QApplication.translate("MainWindow", "&Mask all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnmaskAll.setText(QtGui.QApplication.translate("MainWindow", "&Unmask all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaskLoad.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Enable_all.setText(QtGui.QApplication.translate("MainWindow", "&Enable all", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Disable_all.setText(QtGui.QApplication.translate("MainWindow", "&Disable all", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load_3.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHitRate.setText(QtGui.QApplication.translate("MainWindow", "&Hit Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemoConfig.setText(QtGui.QApplication.translate("MainWindow", "D&emo config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectSPIDR.setText(QtGui.QApplication.translate("MainWindow", "&SPIDR", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectDemo.setText(QtGui.QApplication.translate("MainWindow", "&Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOutputs.setText(QtGui.QApplication.translate("MainWindow", "&Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaskSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrimsSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfiguration.setText(QtGui.QApplication.translate("MainWindow", "Load configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveConfiguration.setText(QtGui.QApplication.translate("MainWindow", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconect.setText(QtGui.QApplication.translate("MainWindow", "&Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectSPIDR_2.setText(QtGui.QApplication.translate("MainWindow", "SPIDR", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemo.setText(QtGui.QApplication.translate("MainWindow", "Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullScreen.setText(QtGui.QApplication.translate("MainWindow", "Full screen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutSPIDR.setText(QtGui.QApplication.translate("MainWindow", "About SPIDR", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSPIDRSettings.setText(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSPIDRAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDummyGenerator.setText(QtGui.QApplication.translate("MainWindow", "Dummy &Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisualisation.setText(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSPIDRSettings1.setText(QtGui.QApplication.translate("MainWindow", "SPIDR", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartWafer.setText(QtGui.QApplication.translate("MainWindow", "Probe &Wafer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionList.setText(QtGui.QApplication.translate("MainWindow", "List:", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProbestationSettings.setText(QtGui.QApplication.translate("MainWindow", "&Probestation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionList_2.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerbose.setText(QtGui.QApplication.translate("MainWindow", "&Verbose", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
