icons.py:Makefile 
	rm -rf icons.py
	echo "from wx.lib.embeddedimage import PyEmbeddedImage\n" > icons.py
	img2py -n fileopen     -i -a icons/fileopen.png     icons.py
	img2py -n settings     -i -a icons/misc.png         icons.py
	img2py -n start        -i -a icons/player_play.png  icons.py
	img2py -n stop         -i -a icons/player_stop.png  icons.py
	img2py -n compfile     -i -a icons/compfile.png      icons.py

	img2py -n gohome       -i -a icons/gohome.png       icons.py
	img2py -n player_eject -i -a icons/player_eject.png icons.py
	img2py -n downarrow    -i -a icons/1downarrow.png   icons.py
	img2py -n leftarrow    -i -a icons/1leftarrow.png   icons.py
	img2py -n rightarrow   -i -a icons/1rightarrow.png  icons.py
	img2py -n uparrow      -i -a icons/1uparrow.png     icons.py
	img2py -n top          -i -a icons/top.png          icons.py
	img2py -n bottom       -i -a icons/bottom.png       icons.py
	img2py -n edit         -i -a icons/edit.png         icons.py
	img2py -n cd           -i -a icons/cd.png           icons.py
